# Generated by Django 6.1 on 2026-09-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='days_interval',
            field=models.PositiveIntegerField(blank=True, help_text="Only used when frequency='custom'. E.g. 3 = every 3 days.", null=True),
        ),
    ]
